version: "3.7"
services:
  product-search-api:
    build: 
      context: .
      dockerfile: src/Services/InfinityLabs.Target.ProductSearch.Api/Dockerfile
    environment: 
      Mongo__ConnectionString: "mongodb://root:example@mongo:27017"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports: 
      - 8080:80
      - 8081:443
  mongo:
    image: mongo:3.4-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 7999:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example